Add support to get Installation identified by its installation id
spotify/github-java-client pull request #151
Opened 2023-10-02 05:06 UTC by miwurster

Hi, this PR adds support to get the an installation's information using the installation id. Essentially, it enables to use the `/app/installations/{installation_id}` [API endpoint](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-installation-for-the-authenticated-app).

2023-12-22 10:22 UTC, ebk45 commented
Hi @miwurster.

We apologise for taking so long to get eyes on this PR, we haven't been able to maintain this library to the standard we would have liked to but this will be changing in the new year. If you could please get this rebased and we'll be prioritising all open PRs ready for review.

Thanks!

Ellie

2023-12-28 07:21 UTC, miwurster commented
Rebased and ready for review.

2023-12-28 09:10 UTC, felix-seifert requested changes
Clear and concise contribution. :+1:

At first sight, I just had to think about what happens if calling the URL results in not finding the installation or gives another bad response. I then saw that this is handled in our `GitHubClient` and does not have to be tested several times.

2023-12-28 09:10 UTC, felix-seifert commented on src/main/java/com/spotify/github/v3/clients/GithubAppClient.java
> +  private static final String GET_INSTALLATION_URL = "/app/installations/%s";
Teeny tiny nitpick. Let's change the string name to clearly differentiate it from the other strings and explain its usage.

```suggestion
  private static final String GET_INSTALLATION_BY_ID_URL = "/app/installations/%s";
```

2023-12-28 09:12 UTC, felix-seifert commented on src/main/java/com/spotify/github/v3/clients/GithubAppClient.java
> +        String.format(GET_INSTALLATION_URL, installationId), Installation.class);
```suggestion
        String.format(GET_INSTALLATION_BY_ID_URL, installationId), Installation.class);
```

2023-12-28 09:15 UTC, felix-seifert approved these changes

2023-12-28 09:17 UTC, merged