BUG SearchIssue id can be bigger than Integer.MAX
spotify/github-java-client pull request #180
Opened 2024-02-22 05:19 UTC by vootelerotov

Represent it as Long instead of Integer.

For schema (where id is specified as 'int64') see:

https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests

2024-02-22 05:19 UTC, vootelerotov commented
Ran into this in the wild.

2024-02-22 05:22 UTC, vootelerotov commented
Hmm, build is failing with `Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65` -- not sure if this is related to my change-set?

2024-02-26 15:51 UTC, vootelerotov commented
It seems that a lot of PR-s now have ID-s that are bigger than `Integer.MAX`, quite easy to run into this in wild now.

2024-06-25 07:54 UTC, weidongxu-microsoft commented
Comment ID could have the same overflow. e.g.
https://api.github.com/repos/Azure/azure-sdk-for-java/issues/comments/2188169837

It maybe safer to convert all ID of `int` type to `long` type.

2024-09-26 07:26 UTC, neeme-praks-sympower commented
Also ran into this.

2024-10-29 16:30 UTC, sheepdreamofandroids commented
Yep, had the same problem. 
This should be merged because the problem is only going to be more frequent.

2025-01-29 11:10 UTC, Abhi347 requested changes
@vootelerotov The PR is good to go if you add the test json file. Please ping me once you have done so.  
Thanks for your contribution

2025-01-29 11:10 UTC, Abhi347 commented on src/test/java/com/spotify/github/v3/search/SearchTest.java
> +        Resources.toString(getResource(this.getClass(), "issues-with-large-id.json"), defaultCharset());
Looks like you forgot to add the `issues-with-large-id.json` file in the test resources. It needs to be added at `src/test/resources/com/spotify/github/v3/issues/issues-with-large-id.json` for this PR to pass.

2025-01-29 13:33 UTC, vootelerotov commented on src/test/java/com/spotify/github/v3/search/SearchTest.java
> +        Resources.toString(getResource(this.getClass(), "issues-with-large-id.json"), defaultCharset());
Doh :(

@Abhi347 I think #200 is a more complete solution with passing tests (thanks @sindunuragarp), happy to close this PR in favour of it.

2025-02-05 13:46 UTC, sindunuragarp commented on src/test/java/com/spotify/github/v3/search/SearchTest.java
> +        Resources.toString(getResource(this.getClass(), "issues-with-large-id.json"), defaultCharset());
@Abhi347 Would be great if one of the two PRs could be merged :)

2025-03-10 09:40 UTC, Abhi347 commented on src/test/java/com/spotify/github/v3/search/SearchTest.java
> +        Resources.toString(getResource(this.getClass(), "issues-with-large-id.json"), defaultCharset());
Merge #200 Closing this now. Thanks for your contribution.

2025-03-10 09:41 UTC, Abhi347 commented
Closing this as another PR (#200) fixing this issue is merged

2025-03-10 09:41 UTC, closed without merging