Add Request Review functions (list, create, remove)
spotify/github-java-client pull request #36
Opened 2020-09-15 05:53 UTC by vglocus

Extend PullRequestClient with methods for listing, creating and removing requested reviews.

Can reach out using viktorg@spotify.com

2020-09-15 09:05 UTC, vglocus commented
@henriquetruta

2020-09-16 08:12 UTC, henriquetruta requested changes
Thanks for your PR! A few suggestions inline

2020-09-16 08:12 UTC, henriquetruta commented on src/main/java/com/spotify/github/v3/clients/PullRequestClient.java
> +    log.debug("Requesting reviews for PR: " + path);
this comment seems to have been copied from the one above

2020-09-16 08:12 UTC, henriquetruta commented on src/main/java/com/spotify/github/v3/clients/PullRequestClient.java
> +
minor: unnecessary new lines

2020-09-16 08:12 UTC, henriquetruta commented on src/main/java/com/spotify/github/v3/clients/PullRequestClient.java
> +  public CompletableFuture<Void> removeRequestedReview(final int number, final RequestReviewParameters properties) {
it'd be nice to add a test for this case, so we can get the new top-level `delete(path, jsonPayload)` method tested as well

2020-09-17 11:04 UTC, vglocus commented
Thank you @henriquetruta. I've fixed your comments and extended the testing somewhat.

2020-09-17 11:07 UTC, henriquetruta approved these changes
Thanks for addressing the comments!

2020-09-17 11:07 UTC, merged